package hello;

import java.util.Optional;
import java.util.concurrent.atomic.AtomicLong;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

@RestController
@RequestMapping(path="/greeting")
public class GreetingController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private GreetingRepository greetingRepository;

    /*
    public Greeting greeting(@RequestParam(value="name", defaultValue="World") String name) {
        return new Greeting(counter.incrementAndGet(),
        String.format(template, name));
    }
    */
    @GetMapping
    public Iterable<Greeting> getAllGreetings(){
        return greetingRepository.findAll();
    }

    @GetMapping(path="/get")
    public Optional<Greeting> getGreetingById(@RequestParam Integer id){
        return greetingRepository.findById(id);
    }

    @PostMapping
    public Greeting addGreeting(@RequestBody Greeting newGreeting){
        return greetingRepository.save(newGreeting);
    }

    @DeleteMapping
    public void deleteGreetingById(@RequestParam Integer id){
        greetingRepository.deleteById(id);
    }

}